### ISSUE TITLE
Error compiling on Ubuntu Willy

### ISSUE THREAD

**Issue by crackfoo** [gongyicoin/gongyicoin#1]
make[3]: Entering directory '/home/crackers/src/gongyicoin/src/secp256k1'
make[3]: 'libsecp256k1.la' is up to date.
make[3]: Leaving directory '/home/crackers/src/gongyicoin/src/secp256k1'
  CXXLD    gongyicoind
/usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libbitcoin_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:2619: recipe for target 'gongyicoind' failed
make[2]: **\* [gongyicoind] Error 1
make[2]: Leaving directory '/home/crackers/src/gongyicoin/src'
Makefile:6556: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/crackers/src/gongyicoin/src'
Makefile:568: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

Any way to fix this?

**Comment by gongyicoin** [comment]
sudo apt-get install build-essential git automake libboost-dev libboost-all-dev openssl libssl-dev libminiupnpc-dev libqrencode-dev libprotobuf-dev protobuf-compiler libgmp-dev autoconf libboost-all-dev libssl-dev libprotobuf-dev protobuf-compiler libqt4-dev libqrencode-dev libtool pkg-config
cd ~
mkdir src
cd src
wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
tar zxvf db-4.8.30.NC.tar.gz
cd db-4.8.30.NC/build_unix
../dist/configure --enable-cxx --with-pic
make
sudo make install
sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb-4.8.so /usr/lib/libdb-4.8.so
sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb_cxx-4.8.so /usr/lib/libdb_cxx-4.8.so
export BDB_INCLUDE_PATH="/usr/local/BerkeleyDB.4.8/include"
export BDB_LIB_PATH="/usr/local/BerkeleyDB.4.8/lib"
export BDB_PREFIX="/usr/local/BerkeleyDB.4.8"
echo "export BDB_INCLUDE_PATH=\"/usr/local/BerkeleyDB.4.8/include\"" >> ~/.bashrc
echo "export BDB_LIB_PATH=\"/usr/local/BerkeleyDB.4.8/lib\"" >> ~/.bashrc
echo "export BDB_PREFIX=\"/usr/local/BerkeleyDB.4.8\"" >> ~/.bashrc
sudo echo "export BDB_INCLUDE_PATH=\"/usr/local/BerkeleyDB.4.8/include\"" >> /etc/bash.bashrc
sudo echo "export BDB_LIB_PATH=\"/usr/local/BerkeleyDB.4.8/lib\"" >> /etc/bash.bashrc
sudo echo "export BDB_PREFIX=\"/usr/local/BerkeleyDB.4.8\"" >> /etc/bash.bashrc
cd ~/src
git clone https://github.com/gongyicoin/gongyicoin
cd gongyicoin
chmod +x autogen.sh libtool
./autogen.sh
./configure CPPFLAGS="-I${BDB_PREFIX}/include/ -O2 -fPIC" LDFLAGS="-L${BDB_PREFIX}/lib/"
make

**Comment by crackfoo** [comment]
Progressed a little bit but still end up with:

make[3]: Entering directory '/home/crackers/src/gongyicoin/src/secp256k1'
make[3]: 'libsecp256k1.la' is up to date.
make[3]: Leaving directory '/home/crackers/src/gongyicoin/src/secp256k1'
  CXXLD    gongyicoind
/usr/bin/ld: crypto/libbitcoin_crypto.a(crypto_libbitcoin_crypto_a-blake.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
crypto/libbitcoin_crypto.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:2619: recipe for target 'gongyicoind' failed
make[2]: *** [gongyicoind] Error 1
make[2]: Leaving directory '/home/crackers/src/gongyicoin/src'
Makefile:6556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/crackers/src/gongyicoin/src'
Makefile:568: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by crackfoo** [comment]
Thanks, issue resolved!

**Comment by crackfoo** [comment]
We've now added GYC to the miners multipool: www.zpool.ca

If you could post that in your language threads, that's be great!

Cheers

**Comment by crackfoo** [comment]
We don't find any blocks for GYC after many hours of mining with X13 algo... is this truly X13?

**Comment by crackfoo** [comment]
I now see this error:

2015-12-01 19:06:32 ERROR: CheckProofOfWork() : hash doesn't match nBits
2015-12-01 19:06:32 ERROR: CheckBlockHeader() : proof of work failed
2015-12-01 19:06:32 ERROR: ProcessNewBlock : CheckBlock FAILED

**Comment by gongyicoin** [comment]
No, it's not X13. Please check the source for details.
